
import { Command } from "#structures/classes/Command";
import {
  ContainerBuilder,
  TextDisplayBuilder,
  SeparatorBuilder,
  SeparatorSpacingSize,
  AttachmentBuilder,
  FileBuilder,
  MessageFlags,
  PermissionFlagsBits,
} from "discord.js";
import * as discordTranscripts from "discord-html-transcripts";
import TicketUI from "#bot/Interface";
import { emoji } from "#config/emoji";

class TranscriptCommand extends Command {
  constructor() {
    super({
      name: "transcript",
      description: "Generate an HTML transcript of this ticket",
      usage: "transcript",
      examples: ["transcript"],
      userPermissions: [],
      botPermissions: ["ReadMessageHistory"],
      cooldown: 10,
      enabledSlash: true,
      slashData: {
        name: "transcript",
        description: "Generate an HTML transcript of this ticket",
      },
    });
  }

  async execute({ ctx }) {
    const guildId = ctx.guild.id;
    const userId = ctx.author.id;

    const ticket = await ctx.client.db.getTicketByChannel(ctx.channel.id);
    if (!ticket) {
      return ctx.reply({
        components: [TicketUI.buildError("Not a Ticket", "This command can only be used inside a ticket channel.")],
        flags: TicketUI.getEphemeralFlags(),
      });
    }

    // Staff check
    const staffRoles = await ctx.client.db.getStaffRoles(guildId);
    const hasStaff = ctx.member.roles.cache.some(r => staffRoles.includes(r.id));
    const hasManage = ctx.member.permissions.has(PermissionFlagsBits.ManageChannels);
    const isOwner = ticket.userId === userId;

    if (!hasManage && !hasStaff && !isOwner) {
      return ctx.reply({
        components: [TicketUI.buildError("Permission Denied", "Only the ticket owner or staff can request a transcript.")],
        flags: TicketUI.getEphemeralFlags(),
      });
    }

    // Loading message
    const loading = await ctx.reply({
      components: [(() => {
        const c = new ContainerBuilder();
        c.addTextDisplayComponents(new TextDisplayBuilder().setContent(`${emoji.transcript} Generating transcript...`));
        return c;
      })()],
      flags: TicketUI.getFlags(),
    });

    try {
      const transcriptBuffer = await discordTranscripts.createTranscript(ctx.channel, {
        limit: -1,
        returnType: "buffer",
        saveImages: false,
        poweredBy: false,
      });

      const fileName = `transcript-${ticket.ticketId}.html`;
      const attachment = new AttachmentBuilder(transcriptBuffer, { name: fileName });

      const container = new ContainerBuilder();
      container.addTextDisplayComponents(
        new TextDisplayBuilder().setContent(
          `## ${emoji.transcript} Transcript Ready\n\n` +
          `**Ticket:** #${ticket.ticketId}\n` +
          `**Channel:** <#${ctx.channel.id}>\n` +
          `**Generated By:** <@${userId}>\n` +
          `**Time:** <t:${Math.floor(Date.now() / 1000)}:F>`
        )
      );
      container.addSeparatorComponents(
        new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Small).setDivider(true)
      );
      container.addFileComponents(
        new FileBuilder().setURL(`attachment://${fileName}`)
      );

      await loading.edit({
        components: [container],
        files: [attachment],
        flags: TicketUI.getFlags(),
        allowedMentions: { parse: [] },
      });
    } catch (err) {
      await loading.edit({
        components: [TicketUI.buildError("Transcript Failed", "Could not generate the transcript. Please try again.")],
        files: [],
        flags: TicketUI.getFlags(),
      });
    }
  }
}

export default new TranscriptCommand();

/**
 * Copyright (c) 2025 Titan X Development
 * Code by Titan X Development
 * MIT License
 */
